name = "polyroots-fortran"
author = "Jacob Williams"
copyright  = "Copyright (c) 2022, Jacob Williams"
license = "BSD-3"
description = "Polynomial Roots with Modern Fortran"
homepage = "https://github.com/jacobwilliams/polyroots-fortran"
keywords = ["root"]

[build]
auto-executables = false
auto-examples = false
auto-tests = true
link = ["lapack", "blas"]

[library]
source-dir = "src"

[install]
library = true